name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: LaTeX compilation
        uses: dante-ev/latex-action@v0.2.0
        with:
          root_file: cv.tex
      
      - name: Add compiled PDF & commit
        uses: EndBug/add-and-commit@v4.4.0
        with:
          add: cv.pdf
          force: true # *.pdf files are usually ignored, but we do want to add this one
          message: "Add compiled PDF"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
